.TH "src/include/ Directory Reference" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBerror\&.h\fP"
.br
.RI "\fICross-platform error logging utilities\&. \fP"
.ti -1c
.RI "file \fBoptions\&.h\fP"
.br
.RI "\fIInterfaces for long and short command-line arguments\&. \fP"
.ti -1c
.RI "file \fBsocket\&.h\fP"
.br
.RI "\fIInterface for cross-patform socket connections\&. \fP"
.ti -1c
.RI "file \fBstrings\&.h\fP"
.br
.RI "\fIInterface for cross-platform string utilities\&. \fP"
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.RI "\fIDefines commonly used type names, enums, includes system types when needed\&. \fP"
.ti -1c
.RI "file \fBverbs\&.h\fP"
.br
.RI "\fIInterface for supported commands\&. \fP"
.in -1c
