.TH "src/include/options.h" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/options.h \- 
.PP
Interfaces for long and short command-line arguments\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <getopt\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBSPINXPI_OPTS\fP \fBSPINXPI_OPTS\fP"
.br
.RI "\fIA structure containing option flags to be set by long and short options\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct option \fBlong_options\fP []"
.br
.RI "\fIA structure containing all long options\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interfaces for long and short command-line arguments\&. 


.PP
Definition in file \fBoptions\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBSPINXPI_OPTS\fP \fBSPINXPI_OPTS\fP"

.PP
A structure containing option flags to be set by long and short options\&. 
.SH "Variable Documentation"
.PP 
.SS "struct option long_options[]"

.PP
A structure containing all long options\&. This structure must be terminated with a 0-row (i\&.e\&. \fC{0,0,0,0}\fP)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
