.TH "src/peer.c" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peer.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <strings\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBt_verbs\fP"
.br
.ti -1c
.RI "struct \fBt_opts\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_help\fP (char **, struct \fBt_verbs\fP *)"
.br
.ti -1c
.RI "void \fBprint_version\fP ()"
.br
.ti -1c
.RI "void \fBprint_usage\fP (char **, struct \fBt_verbs\fP *, int)"
.br
.ti -1c
.RI "void \fBprint_suggest_help\fP (char **)"
.br
.ti -1c
.RI "void \fBconsume_args\fP (struct \fBt_opts\fP *, struct \fBt_verbs\fP *, int, char **)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void consume_args (struct \fBt_opts\fP *o_flags, struct \fBt_verbs\fP *v_flags, intargc, char **argv)"

.PP
Definition at line 147 of file peer\&.c\&.
.SS "int main (intargc, char **argv)"

.PP
Definition at line 25 of file peer\&.c\&.
.SS "void print_help (char **argv, struct \fBt_verbs\fP *v_flags)"

.PP
Definition at line 84 of file peer\&.c\&.
.SS "void print_suggest_help (char **argv)"

.PP
Definition at line 143 of file peer\&.c\&.
.SS "void print_usage (char **argv, struct \fBt_verbs\fP *v_flags, intsuggest_help)"

.PP
Definition at line 126 of file peer\&.c\&.
.SS "void print_version ()"

.PP
Definition at line 110 of file peer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
