.TH "SPINXPI_SOCKADDR" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPINXPI_SOCKADDR \- 
.PP
Contains a socket connection inforation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBhost\fP"
.br
.RI "\fIThe host name for this socket\&. \fP"
.ti -1c
.RI "int \fBport\fP"
.br
.RI "\fIThe port number to bind this socket\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains a socket connection inforation\&. 
.PP
Definition at line 39 of file socket\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* SPINXPI_SOCKADDR::host"

.PP
The host name for this socket\&. 
.PP
Definition at line 40 of file socket\&.h\&.
.SS "int SPINXPI_SOCKADDR::port"

.PP
The port number to bind this socket\&. 
.PP
Definition at line 41 of file socket\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
