.TH "SPINXPI_SOCK" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPINXPI_SOCK \- 
.PP
Contains a socket inforation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsockfd\fP"
.br
.RI "\fIA file descriptor for this socket\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains a socket inforation\&. 
.PP
Definition at line 47 of file socket\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int SPINXPI_SOCK::sockfd"

.PP
A file descriptor for this socket\&. 
.PP
Definition at line 48 of file socket\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
