.TH "src/include/strings.c" 3 "Thu Jul 30 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/strings.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_H_STRINGS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBSPIN_strlen\fP (char *str)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _H_STRINGS"

.PP
Definition at line 2 of file strings\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int SPIN_strlen (char *str)"
Computes length of a cstring 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP the string 
.RE
.PP
\fBReturns:\fP
.RS 4
an integer length 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
