.TH "src/include/strings.h" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/strings.h \- 
.PP
Interface for cross-platform string utilities\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBstrlen\fP (char *str)"
.br
.RI "\fIcalculates the length of a string \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface for cross-platform string utilities\&. 


.PP
Definition in file \fBstrings\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int strlen (char *str)"

.PP
calculates the length of a string \fBParameters:\fP
.RS 4
\fIstr\fP a string 
.RE
.PP
\fBReturns:\fP
.RS 4
an integer length 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
