.TH "t_verbs" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_verbs \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBnames\fP [6]"
.br
.ti -1c
.RI "int \fBinit\fP"
.br
.ti -1c
.RI "int \fBdestroy\fP"
.br
.ti -1c
.RI "int \fBvc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file peer\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int t_verbs::destroy"

.PP
Definition at line 11 of file peer\&.c\&.
.SS "int t_verbs::init"

.PP
Definition at line 10 of file peer\&.c\&.
.SS "char* t_verbs::names[6]"

.PP
Definition at line 9 of file peer\&.c\&.
.SS "int t_verbs::vc"

.PP
Definition at line 12 of file peer\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
