.TH "src/include/types.h" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/types.h \- 
.PP
Defines commonly used type names, enums, includes system types when needed\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBSPINXPI_RESULT\fP \fBSPINXPI_RESULT\fP"
.br
.RI "\fIA POSIX style return value with 0 bound to success, -1 to failure\&. \fP"
.ti -1c
.RI "typedef enum \fBSPINXPI_BOOL\fP \fBSPINXPI_BOOL\fP"
.br
.RI "\fIA boolean type modelled after standard libraries\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSPINXPI_RESULT\fP { \fBSPINXPI_FAIL\fP =  -1, \fBSPINXPI_OK\fP =  0 }"
.br
.RI "\fIA POSIX style return value with 0 bound to success, -1 to failure\&. \fP"
.ti -1c
.RI "enum \fBSPINXPI_BOOL\fP { \fBSPINXPI_FALSE\fP =  0, \fBSPINXPI_TRUE\fP =  1 }"
.br
.RI "\fIA boolean type modelled after standard libraries\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines commonly used type names, enums, includes system types when needed\&. 


.PP
Definition in file \fBtypes\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBSPINXPI_BOOL\fP  \fBSPINXPI_BOOL\fP"

.PP
A boolean type modelled after standard libraries\&. 
.SS "typedef enum \fBSPINXPI_RESULT\fP  \fBSPINXPI_RESULT\fP"

.PP
A POSIX style return value with 0 bound to success, -1 to failure\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSPINXPI_BOOL\fP"

.PP
A boolean type modelled after standard libraries\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISPINXPI_FALSE \fP\fP
A constant corresponding to boolean \fCfalse\fP 
.TP
\fB\fISPINXPI_TRUE \fP\fP
A constant corresponsing to boolean \fCtrue\fP 
.PP
Definition at line 42 of file types\&.h\&.
.SS "enum \fBSPINXPI_RESULT\fP"

.PP
A POSIX style return value with 0 bound to success, -1 to failure\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISPINXPI_FAIL \fP\fP
A result value constant meaning 'failure'\&. 
.TP
\fB\fISPINXPI_OK \fP\fP
A result value constant meaning 'no error'\&. 
.PP
Definition at line 34 of file types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
