.TH "src/include/verbs.h" 3 "Fri Jul 31 2015" "Version 0.1.0-SNAPSHOT" "SPIN Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/verbs.h \- 
.PP
Interface for supported commands\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBSPINXPI_VERBS\fP \fBSPINXPI_VERBS\fP"
.br
.RI "\fIA structure containing verb flags to be implemented\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface for supported commands\&. 


.PP
Definition in file \fBverbs\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBSPINXPI_VERBS\fP \fBSPINXPI_VERBS\fP"

.PP
A structure containing verb flags to be implemented\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SPIN Framework from the source code\&.
